#\DeclareLyXModule{Initials (Drop Caps)}
#\DeclareCategory{Paragraph Styles}
#DescriptionBegin
#Defines a style for paragraphs with an enlarged initial letter (drop cap).
#See the EmbeddedObjects manual for a detailed description.
#DescriptionEnd
#Authors: Pavel Sanda and Uwe Stöhr

Format 104

AddToPreamble
	\@ifundefined{lettrine}{\usepackage{lettrine}}{}
EndPreamble

InsetLayout Flex:Initial
	LyxType		charstyle
	LabelString	"Initial"
	LatexType	command
	LatexName	lettrine
	Font
	  Size		Large
	EndFont
	Requires	lettrine
	ResetsFont  true
    DocBookTag             para
    DocBookAttr            role='hanging'
End

Style Initial
	Category	MainText
	LatexType	command
	LatexName	lettrine
	Margin		First_Dynamic
	LabelType	static
	LabelString	Initial
	Argument 1
	  LabelString	"Options"
	  Tooltip	"Option(s) for the initial"
	  DocBookTag    NONE
	EndArgument
	Argument 2
	  Mandatory	1
	  LabelString	"Initial"
	  Tooltip	"Initial letter(s)"
	  DocBookTag      phrase
	  DocBookAttr     role='initial'
	  DocBookTagType  inline
	EndArgument
	Argument 3
	  Mandatory	1
	  LabelString	"Rest of Initial"
	  Tooltip	"Rest of initial word or text"
	  DocBookTag      phrase
	  DocBookAttr     role='rest-of-initial'
	  DocBookTagType  inline
	EndArgument
	LabelSep	x
	ParIndent	MMM
	ParSkip		0.4
	TopSep		0.7
	BottomSep	0.7
	ParSep		0.3
	Align		Left
	AlignPossible	Left
	LabelFont
	  Series	Bold
	EndFont
    DocBookTag             para
    DocBookAttr            role='paragraph-with-initial'
End

