#\DeclareLyXModule[multicol.sty]{Multiple Columns}
#\DeclareCategory{Page Layout}
#DescriptionBegin
#Adds a custom inset whose content is set with multiple columns (2 by default).
#See the Additional manual, section Modules > Page Layout > Multiple Columns,
#for a detailed description.
#DescriptionEnd
#Authors: Uwe Stöhr and Jürgen Spitzmüller

Format 104

InsetLayout Flex:Multiple_Columns
  LyXType			custom
  Decoration		classic
  LabelString		Columns
  LatexType			environment
  LatexName			multicols
  Requires			multicol
  Argument 1
    LabelString		"Number of Columns"
    Tooltip			"Insert the number of columns here"
    Mandatory		1
    DefaultArg		2
    PassThru		1
	DocBookTag      IGNORE
  EndArgument
  Argument 2
    LabelString		"Preface"
    Tooltip			"An optional preface"
	DocBookTag      para
	DocBookAttr     role='preface'
	DocBookArgumentBeforeMainTag  true
  EndArgument
  Argument 3
    LabelString		"Space Before Page Break"
    Tooltip			"Free space that needs to be on the page to start the multiple columns on this page"
    Requires		2
	DocBookTag      IGNORE
  EndArgument
  ResetsFont        true

  # The current DocBook implementation is quite lacking, but it would require
  # a lot more C++ code to have perfect output. The major problem: not all
  # elements within a column should be wrapped in an item. It has been
  # designed for pure text (like in Modules > Page Layout > Multiple Columns,
  # the excerpt of "The Adventure of the Empty House"), it produces wrong
  # output for lists (such as Document classes > Articles > Astronomy >
  # Supported environments, the Columns flex only contains a list). Columns
  # within columns are not supported either (as in Modules > Page Layout >
  # Multiple Columns > Columns inside Columns).
  DocBookWrapperTag NONE
  DocBookTag        NONE
  DocBookNotInPara  true
  DocBookItemTag    para
End

