#\DeclareLyXModule{Standard Theorems}
#\DeclareCategory{Maths}
#DescriptionBegin
#Defines some theorem environments for use with non-AMS classes. By default, 
#the theorems are numbered consecutively throughout the document. This can be
#changed by loading one of the 'Theorems (Numbered by ...)' modules.
#DescriptionEnd
#Excludes: theorems-ams | theorems-starred

# Author: Richard Kimberly Heck <rikiheck@lyx.org>

Format 104

Counter theorem
	GuiName Theorem
	LaTeXName thm
	RefFormat thm "Theorem \arabic{theorem}"
	RefFormat cor "Corollary \arabic{theorem}"
	RefFormat lem "Lemma \arabic{theorem}"
	RefFormat prop "Proposition \arabic{theorem}"
	RefFormat conj "Conjecture \arabic{theorem}"
	RefFormat fact "Fact \arabic{theorem}"
	RefFormat def "Definition \arabic{theorem}"
	RefFormat exa "Example \arabic{theorem}"
	RefFormat prob "Problem \arabic{theorem}"
	RefFormat exer "Exercise \arabic{theorem}"
	RefFormat solu "Solution \arabic{theorem}"
	RefFormat rem "Remark \arabic{theorem}"
	RefFormat claim "Claim \arabic{theorem}"
End

Input theorems.inc
Input theorems-proof.inc
Input theorems-proof-std.inc
