# Theorem-like counters, extended, separately for each type of theorem

Format 104
Counter criterion
	GuiName Criterion
	PrettyFormat "Criterion \arabic{theorem}"
End
Counter algorithm
	GuiName Algorithm
	LaTeXName lyxalgorithm
	PrettyFormat "Algorithm \arabic{theorem}"
End
Counter axiom
	GuiName Axiom
	LaTeXName ax
	PrettyFormat "Axiom \arabic{theorem}"
End
Counter condition
	GuiName Condition
	PrettyFormat "Condition \arabic{theorem}"
End
Counter note
	GuiName Note
	PrettyFormat "Note \arabic{theorem}"
End
Counter notation
	GuiName Notation
	PrettyFormat "Notation \arabic{theorem}"
End
Counter summary
	GuiName Summary
	PrettyFormat "Summary \arabic{theorem}"
End
Counter conclusion
	GuiName Conclusion
	PrettyFormat "Conclusion \arabic{theorem}"
End
Counter assumption
	GuiName Assumption
	PrettyFormat "Assumption \arabic{theorem}"
End
Counter question
	GuiName Question
	PrettyFormat "Question \arabic{theorem}"
End
