#\DeclareLyXModule{AMS Theorems}
#\DeclareCategory{Maths}
#DescriptionBegin
#Defines theorem environments and the proof environment using the extended 
#AMS machinery. Both numbered and unnumbered types are provided. By default, 
#the theorems are numbered consecutively throughout the document. This can be
#changed by loading one of the 'Theorems (Numbered by ...)' modules.
#DescriptionEnd
#Excludes: theorems-std | theorems-starred

# Original Author : David L. Johnson <dlj0@lehigh.edu>
# Probably broken by Jean-Marc Lasgouttes <Jean-Marc.Lasgouttes@inria.fr>
# modified and modularized by Emmanuel GUREGHIAN <gureghia@boston.bertin.fr>
# Tinkered with Sep. '07 by Paul Rubin <rubin@msu.edu>
# Modularized Jan 08 by Richard Kimberly Heck <rikiheck@lyx.org>

Format 104

Requires	amsmath,amsthm

Counter theorem
	GuiName Theorem
	LaTeXName thm
	RefFormat thm "Theorem \arabic{theorem}"
	RefFormat cor "Corollary \arabic{theorem}"
	RefFormat lem "Lemma \arabic{theorem}"
	RefFormat prop "Proposition \arabic{theorem}"
	RefFormat conj "Conjecture \arabic{theorem}"
	RefFormat def "Definition \arabic{theorem}"
	RefFormat exa "Example \arabic{theorem}"
	RefFormat prob "Problem \arabic{theorem}"
	RefFormat exer "Exercise \arabic{theorem}"
	RefFormat solu "Solution \arabic{theorem}"
	RefFormat rem "Remark \arabic{theorem}"
	RefFormat claim "Claim \arabic{theorem}"
	RefFormat fact "Fact \arabic{theorem}"
	RefFormat cri "Criterion \arabic{theorem}"
	RefFormat alg "Algorithm \arabic{theorem}"
End

Input theorems-order.inc
Input theorems-ams.inc
Input theorems-starred.inc
Input theorems-proof.inc
